config/routes.rb
Catarse::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => {:registrations => "registrations", :passwords => "passwords"} do
    get "/login" => "devise/sessions#new"
    get "/interests" => "users#interests", :as => "user_interests"
  end

  # Non production routes
  if Rails.env == "test"
    match "/fake_login" => "sessions#fake_create", :as => :fake_login
  elsif Rails.env == "development"
    resources :emails, :only => [ :index ]
  end

  mount CatarseMoip::Engine => "/", :as => "catarse_moip"

  filter :locale

  root to: 'projects#index'

  match "/reports/financial/:project_id/backers" => "reports#financial_by_project", :as => :backers_financial_report
  match "/reports/attendance/:project_id/backers" => "reports#attendance_by_project", :as => :backers_attendance_report
  match "/reports/location/:project_id/backers" => "reports#location_by_project", :as => :backers_location_report
  match "/reports/users_most_backed" => "reports#users_most_backed", :as => :most_backed_report
  match "/reports/all_confirmed_backers" => "reports#all_confirmed_backers", :as => :all_confirmed_backers_report
  match "/reports/all_projects_owners" => "reports#all_projects_owner", :as => :all_projects_owner_report
  match "/reports/all_emails" => "reports#all_emails_to_newsletter", :as => :all_emails_to_newsletter
  match "/reports/projects_monthly" => "reports#projects_monthly", :as => :projects_monthly

  # Static Pages
  match '/sitemap' => "static#sitemap", :as => :sitemap
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/terms" => "static#terms", :as => :terms
  match "/privacy" => "static#privacy", :as => :privacy
  match "/about_us" => "static#about_us", :as => :about_us
  match "/contact" => "static#contact", :as => :contact

  match "/thank_you" => "payment_stream#thank_you", :as => :thank_you
  match "/moip" => "payment_stream#moip", :as => :moip
  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  post "/auth" => "sessions#auth", :as => :auth
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout
  resources :posts, only: [:index, :create]
  resources :projects, only: [:index, :new, :create, :show, :update] do
    resources :updates, :only => [:index, :create, :destroy]
    resources :rewards
    resources :backers, controller: 'projects/backers' do
      collection do
        post 'review'
      end
      member do
        put 'checkout'
      end
    end
    collection do
      get 'vimeo'
      get 'cep'
      get 'pending'
      get 'pending_backers'
      get 'thank_you'
      post 'update_attribute_on_the_spot'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    member do
      get 'projects'
      get 'credits'
    end
    post 'update_attribute_on_the_spot', :on => :collection
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  resources :curated_pages do
    collection do
      post 'update_attribute_on_the_spot'
    end
  end
  match "/pages/:permalink" => "curated_pages#show", as: :curated_page

  match "/beta" => redirect("http://nos.vc")
  namespace :adm do
    resources :backers do
      collection do
        post 'update_attribute_on_the_spot'
      end
    end
    resources :users
  end

  resources :tests

  match "/:permalink" => "projects#show", as: :project_by_slug

end

app/controllers/projects/backers_controller.rb
# Encoding: utf-8
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :new
  before_filter :load_project

  def index
    @backers = @project.backers.confirmed.order("confirmed_at DESC").page(params[:page]).per(20)

    respond_to do |format|
      format.html { redirect_to(login_path) unless can?(:manage_backers, @project) }
      format.json { render :json => @backers.to_json(:can_manage => can?(:manage, @project)) }
    end
  end

  def new
    return unless require_login
    unless @project.can_back?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end
    @title = t('projects.backers.new.title', :name => @project.name)
    @backer = @project.backers.new(:user => current_user)
    #empty_reward = Reward.new(:id => 0, :minimum_value => 0, :description => t('projects.backers.new.no_reward'))
    @rewards = []
    if session[:token].present?
      @rewards = @project.rewards.with_token session[:token]
    end
    @rewards.concat @project.rewards.not_expired.order(:minimum_value).public
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def review
    return unless require_login

    @title = t('projects.backers.review.title')
    params[:backer][:reward_id] = nil if params[:backer][:reward_id] == '0'
    params[:backer][:user_id] = current_user.id
    @project = Project.find params[:project_id]
    backer_data = params[:backer]
    backer_data[:value] = Reward.find(backer_data[:reward_id]).minimum_value
    @backer = @project.backers.new(backer_data)

    unless @backer.save
      raise @backer.errors.inspect
      flash[:failure] = t('projects.backers.review.error')
      return redirect_to new_project_backer_path(@project)
    end
    if @backer.project.has_dynamic_fields?
      @backer.project.dynamic_fields.order(:created_at).each do |dynamic_field|
        @backer.dynamic_values.build dynamic_field_id: dynamic_field.id
      end
    end
    session[:thank_you_id] = @project.id
  end

  def checkout
    return unless require_login
    backer = current_user.backs.find params[:id]
    session[:token] = nil # remove the token of reward
    # reward free
    if backer.value == 0
      current_user.update_attributes params[:user]
      update_dynamic_values_attributes backer
      unless backer.confirmed
        backer.update_attribute :payment_method, 'Free'
        backer.confirm!
      end
      flash[:success] = t('projects.backers.checkout.success')
      return redirect_to thank_you_path
    end

    if params[:payment_method_url].present?
      current_user.update_attributes params[:user]
      current_user.reload
      update_dynamic_values_attributes backer
      return redirect_to params[:payment_method_url]
    else
      if backer.credits
        if current_user.credits < backer.value
          flash[:failure] = t('projects.backers.checkout.no_credits')
          return redirect_to new_project_backer_path(backer.project)
        end
        unless backer.confirmed
          current_user.credits = (current_user.credits - backer.value)
          current_user.save
          backer.update_attributes({ payment_method: 'Credits' })
          backer.confirm!
        end
        flash[:success] = t('projects.backers.checkout.success')
        redirect_to thank_you_path
      end
    end
  end

  private
  def update_dynamic_values_attributes backer
    backer.update_attributes({:dynamic_values_attributes => params[:backer][:dynamic_values_attributes]}) if params[:backer].present? and params[:backer][:dynamic_values_attributes].present?
  end
  def load_project
    @project = Project.find params[:project_id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  include ActionView::Helpers::DateHelper

  include ActiveModel::ForbiddenAttributesProtection

  inherit_resources
  actions :index, :show, :new, :create, :update
  respond_to :html, :except => [:backers]
  respond_to :json, :only => [:index, :show, :backers]
  can_edit_on_the_spot
  skip_before_filter :detect_locale, :only => [:backers]
  before_filter :can_update_on_the_spot?, :only => :update_attribute_on_the_spot
  before_filter :date_format_convert, :only => [:create]

  before_filter :load_past_locations, :only => [:new]

  def date_format_convert
    # TODO localize here and on the datepicker on project_form.js
    params["project"]["expires_at"] = Date.strptime(params["project"]["expires_at"], '%d/%m/%Y')
    params["project"]["rewards_attributes"].each_with_index do |value, index|
      params["project"]["rewards_attributes"][index.to_s]["expires_at"] = Date.strptime(params["project"]["rewards_attributes"][index.to_s]["expires_at"], '%d/%m/%Y') + 23.hours + 59.minutes if params["project"]["rewards_attributes"][index.to_s]["expires_at"].present?
    end
  end

  def index
    index! do |format|
      format.html do
        @title = t("site.title")

        @curated_pages = CuratedPage.visible.order("created_at desc")
        collection_projects = Project.recommended_for_home
        unless collection_projects.empty?
          @first_project, @second_project, @third_project, @fourth_project = collection_projects.all
        end

        project_ids = collection_projects.map{|p| p.id }

        @expiring = Project.expiring_for_home(project_ids)
        @recent = Project.recent_for_home(project_ids)

        @blog_posts = Blog.fetch_last_posts.inject([]) do |total,item|
          if total.size < 2
            total << item
          end
          total
        end || []

        @curated_pages = CuratedPage.visible.order("created_at desc").limit(8)
      end
      format.json do
        # After the search params we order by ID to avoid ties and therefore duplicate items in pagination
        @projects = Project.visible.search(params[:search]).order('id').page(params[:page]).per(6)
        respond_with(@projects)
      end
    end
  end

  def new
    return unless require_login
    new! do
      @title = t('projects.new.title').gsub(/<\/?[^>]*>/, "")
      @project.rewards.build
      @project.dynamic_fields.build()
    end
  end

  def create
    params[:project][:expires_at] += (23.hours + 59.minutes + 59.seconds) if params[:project][:expires_at]
    validate_rewards_attributes if params[:project][:rewards_attributes].present?
    params[:project].delete(:dynamic_fields_attributes) unless params[:has_dynamic_fields]
    create!{ |format|
      format.html { redirect_to root_path, :notice => t('projects.create.success') }
    }
    # When it can't create the project the @project doesn't exist and then it causes a record not found
    # because @project.reload *works only with created records*
    unless @project.new_record?
      @project.reload
      @project.update_attributes({ short_url: bitly })
      ProjectsMailer.new_project(params[:project][:name], project_url(@project), @project, current_user).deliver
    end
  end

  def update
    update! { project_path(@project) }
  end

  def show
    begin
      if params[:permalink].present?
        @project = Project.find_by_permalink! params[:permalink]
      elsif resource.permalink.present?
        return redirect_to project_by_slug_path(resource.permalink)
      end

      @project = Project.find params[:id] if params[:id].present?
      @link = @project
      if !params[:permalink].present? and @project.permalink.present?
        @link = project_by_slug_url(permalink: @project.permalink)
        return redirect_to project_by_slug_url(permalink: @project.permalink)
      end

      if params[:token].present?
        session[:token] = params[:token]
        return redirect_to @link
      end

      show!{
        @rewards = []
        if session[:token].present?
          @rewards = @project.rewards.with_token session[:token]
        end
        @title = @project.name
        @rewards.concat @project.rewards.order(:minimum_value).public
        @backers = @project.backers.confirmed.limit(12).order("confirmed_at DESC").all
        fb_admins_add(@project.user.facebook_id) if @project.user.facebook_id
      }
    rescue ActiveRecord::RecordNotFound
      return render_404
    end
  end

  def vimeo
    project = Project.new(:video_url => params[:url])
    if project.vimeo.info
      render :json => project.vimeo.info.to_json
    else
      render :json => {:id => false}.to_json
    end
  end

  def cep
    address = BuscaEndereco.por_cep(params[:cep])
    render :json => {
      :ok => true,
      :street => "#{address[0]} #{address[1]}",
      :neighbourhood => address[2],
      :state => address[3],
      :city => address[4]
    }.to_json
  rescue
    render :json => {:ok => false}.to_json
  end

  def embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def video_embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def pending
    return unless require_admin
    @title = t('projects.pending.title')
    @search = Project.search(params[:search])
    @projects = @search.order('projects.created_at DESC').page(params[:page])
  end

  def pending_backers
    return unless require_admin
    @title = t('projects.pending_backers.title')
    @search = Backer.search(params[:search])
    @backers = @search.order("created_at DESC").page(params[:page])
  end


  private

  # Used to show other past event locations to the users
  # in the project creation form
  def load_past_locations
    id = current_user.try(:id)
    past_projects = Project.where('leader_id = ? OR user_id = ?', id, id).order('created_at DESC').limit(3)
    @past_locations = past_projects.pluck(:location).uniq
  end

  # Just to fix a minor bug,
  # when user submit the project without some rewards.
  def validate_rewards_attributes
    rewards = params[:project][:rewards_attributes]
    rewards.each do |r|
      rewards.delete(r[0]) unless Reward.new(r[1]).valid?
    end
  end

  def bitly
    return unless Rails.env.production?
    require 'net/http'
    res = Net::HTTP.start("api.bit.ly", 80) { |http| http.get("/v3/shorten?login=nosvc&apiKey=R_2ba4fd974ddbfe4fe60c997860a9a3f8&longUrl=#{CGI.escape(project_url(@project))}") }
    data = JSON.parse(res.body)['data']
    data['url'] if data
  end

  def can_update_on_the_spot?
    project_fields = ["name", "about", "headline", "expires_at_spot", "image_url", "video_url", "location", "when_short", "when_long", "leader_bio", "maximum_backers", "goal"]
    project_admin_fields = ["name", "about", "headline", "can_finish", "expires_at_spot", "user_id", "image_url", "video_url", "visible", "rejected", "recommended", "home_page",  "permalink", "when_short", "when_long", "leader_bio", "leader_id", "location", "paid"]
    backer_fields = ["display_notice"]
    backer_admin_fields = ["confirmed", "requested_refund", "refunded", "anonymous", "user_id"]
    reward_fields = ["description", "minimum_value", "maximum_backers"]
    reward_admin_fields = ["description", "minimum_value", "maximum_backers"]
    def render_error; render :text => t('require_permission'), :status => 422; end
    return render_error unless current_user
    klass, field, id = params[:id].split('__')
    return render_error unless klass == 'project' or klass == 'backer' or klass == 'reward'
    if klass == 'project'
      return render_error unless project_fields.include?(field) or (current_user.admin and project_admin_fields.include?(field))
      project = Project.find id
      return render_error unless current_user.can_manage_project?(project) or current_user.admin
    elsif klass == 'backer'
      return render_error unless backer_fields.include?(field) or (current_user.admin and backer_admin_fields.include?(field))
      backer = Backer.find id
      return render_error unless current_user.admin or (backer.user == current_user)
    elsif klass == 'reward'
      return render_error unless reward_fields.include?(field) or (current_user.admin and reward_admin_fields.include?(field))
      reward = Reward.find id
      return render_error unless current_user.can_manage_project?(reward.project) or current_user.admin
    end
  end

  # Started migrating stuff for usage with strong_parameters and newer rails standards
  # For the moment this is only called on update by inherited resources
  def permitted_params
    params.permit(:project => [
        :name, :user_id, :category_id, :goal, :expires_at, :about, :headline, {:tag_list => []}, :leader_bio,
        :leader_id, :video_url, :image_url, :logo, :when_short, :when_long, :location, :maximum_backers, {
          :rewards_attributes => [:description, :minimum_value, :maximum_backers, :expires_at, :private],
          :dynamic_fields_attributes => [:input_name, :required]
        }
      ]
    )
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def preview_mode?
    params[:preview] == 'true'
  end

  def show_edit_field
    can?(:edit, @project) && !preview_mode?
  end

  # For the 'past locations' section, generates a list
  # of span tas to be shown
  def generate_location_tags locations
    location_tags = locations.map do |location|
      content_tag :span, location, :class => 'past-location'
    end

    if location_tags.size == 1
      location_tags.first # return the only tag
    else
      # when there are multiple tags join them (the last one is different too)
      last_tag = location_tags.pop

      "#{location_tags.join(', ')} ou #{last_tag}"
    end
  end

end

app/views/projects/_facebook_sdk.html.erb
<div id="fb-root"></div><script type="text/javascript">(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=<%= ENV['FACEBOOK_KEY']%>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/projects/_footer_featured.html.slim
.footer_featured
  .content
    .mi_casa_su_casa
      .title= t('.mi_casa_su_casa.title')
      p= t('.mi_casa_su_casa.text')
      = link_to t('.mi_casa_su_casa.link'), "https://nosvc.typeform.com/to/GWN3Fa"

    .not_repress
      .title= t('.not_repress.title')
      p= t('.not_repress.text')
      = form_tag 'http://nosvc.mailee.me/go/add_contact_form', id: 'mailee-form', method: 'post' do
        = hidden_field_tag 'key', '0699c9'
        = hidden_field_tag 'url_ok', "http://#{request.env['HTTP_HOST']}/?newsletter=ok"
        = hidden_field_tag 'url_error', "http://#{request.env['HTTP_HOST']}/?newsletter=error"
        = text_field_tag 'email', nil, placeholder: 'email@email.com'
        = submit_tag "OK"

    .it_will
      .title= t('.it_will.title')
      p= t('.it_will.text')
      = link_to t('.it_will.link'), t('site.blog'), target: "_blanck"
    .clearfix

app/views/projects/_show_embed.html.slim
- box_width = "905px"
- box_height = "240px"
- video_width = "364px"
- video_height = "415px"
#embed_overlay.overlay.hide
  #project_embed.hide
    a.close[href='#closed_embed']  X
    #project_box_embed
      iframe[frameborder='0' height=box_height width=box_width src=embed_project_path(@project)]
      form.html= text_area_tag 'project_box_embed_html', '<iframe frameborder="0" height="' + box_height + '" src="' + embed_project_url(@project) + '" width="' + box_width + '"></iframe>', :readonly => true
    /#project_video_embed
      /iframe[frameborder='0' height=video_height width=video_width src=video_embed_project_path(@project)]
      /form.html= text_area_tag 'project_video_embed_html', '<iframe frameborder="0" height="' + video_height + '" src="' + video_embed_project_url(@project) + '" width="' + video_width + '"></iframe>', :readonly => true
    .clearfix

app/views/projects/_slider_top.html.slim
.slider_wrapper
  .container
    .slider
      .content.explore
        = link_to explore_path do
          .title = t('slider.top.explore.title')
          p = t('slider.top.explore.text').html_safe
      .content.create
        = link_to new_project_path do
          .title = t('slider.top.create.title')
          p = t('slider.top.create.text').html_safe
      .content.how_works
        = link_to guidelines_path do
          .title = t('slider.top.how_works.title')
          p = t('slider.top.how_works.text').html_safe

app/views/projects/embed.html.haml
#embed
  = render :partial => 'box', :locals => { :project => @project, :embed_link => true }

app/views/projects/index.html.slim
- content_for :meta_tags do
  -# Meta tags for facebook social graph
  meta[property="og:title" content="#{@title}#{' · ' if @title}#{t('site.name')}"]
  meta[property="og:type" content='cause']
  meta[property="og:url" content=root_url]
  meta[property="og:image" content="#{t('site.base_url')}/assets/home_small.png"]
  meta[property="og:site_name" content=t('site.name')]

#page_content
  -# if has_institutional_videos?
  -#  = render 'layouts/institutional_video_header'
  = render 'layouts/call_to_action_header'
  = render 'slider_top'
  .container
    .main
      .selected_projects.list
        .list_title
          .title
            h2
              = t('sections.selection.title')
              p = t('sections.selection.description')
        .projects
          = render :partial => 'project', :locals => {:project => @first_project, :custom_class => 'first' } if @first_project
          = render :partial => 'project', :locals => {:project => @second_project } if @second_project
          = render :partial => 'project', :locals => {:project => @third_project, :custom_class => 'last' } if @third_project
        .explore_link
          hr
          = link_to t('main.links.selected'), explore_path()+"#recommended"

      - if @expiring.count > 0
        .expiring_projects.list
          .list_title
            .title
              h2
                = t('sections.expiring.title')
                p = t('sections.expiring.description')
          .projects
            - @expiring.each_with_index do |item,i|
              == render 'project', :project => item, :custom_class => ((@expiring.length == (i+1) ? 'last' : false) || (i==0 ? 'first' : false))
          .explore_link
            hr
            = link_to t('main.links.expiring'), explore_path()+'#expiring'
      - if @recent.count > 0
        .recents_projects.list
          .list_title
            .title
              h2
                = t('sections.recents.title')
                p = t('sections.recents.description')
          .projects
            - @recent.each_with_index do |item,i|
              == render 'project', :project => item, :custom_class => ((@recent.length == (i+1) ? 'last' : false) || (i==0 ? 'first' : false))
          .explore_link
            hr
            = link_to t('main.links.recents'), explore_path()+'#recent'
    .clearfix
  /= render 'footer_featured'
  = render :partial => 'curated_pages_list', :locals => {:curated_pages => @curated_pages} unless @curated_pages.empty?

app/views/projects/pending.html.slim
#page_content
  .container.container-wide
    .project_content
      .title
        h1= t('.title')

      #pending_projects
        .bootstrap-form
          = form_for @search, :url => pending_projects_path do |f|
            fieldset
              .input
                = f.text_field :id_equals, :placeholder => t('.id')
              .input
                = f.text_field :name_contains, :placeholder => t('.name')
              .input
                = f.text_field :user_name_contains, :placeholder => t('.user')

            fieldset
              .input.check
                = f.check_box :visible_is_true
                = f.label :visible_is_true, t('.visible')
              /.input.check
              /  = f.check_box :rejected_is_true
              /  = f.label :rejected_is_true, t('.rejected')
              /.input.check
              /  = f.check_box :recommended_is_true
              /  = f.label :recommended_is_true, t('.recommended')
              .input.check
                = f.check_box :successful_is_true
                = f.label :successful_is_true, t('.success')
              .input.check
                = f.check_box :can_finish_is_true
                = f.label :can_finish_is_true, t('.can_finish')
              .input.check
                = f.check_box :finished_is_true
                = f.label :finished_is_true, t('.finished')
              .input.check
                = f.check_box :paid_is_true
                = f.label :paid_is_true, t('.paid')

              .bootstrap-twitter
                .input.submit
                  = f.submit t('.submit'), class: 'btn btn-success'

        .total_results
          #total_results
            = pluralize_without_number @search.count, t('found_singular'), t('found_plural')
            strong= " #{@search.count} "
            = pluralize_without_number @search.count, t('activerecord.models.project').downcase

        .clearfix

        = paginate @projects
        .clear

        - if @projects.empty?
          = t('.no_projects')
        - else
          .bootstrap-twitter
            table.table.table-striped
              thead
                tr
                  th= t('.id')
                  th= t('.project')
                  th= t('.when_short')
                  th= t('.expires_at')
                  th= t('.deadline')
                  th= t('.user')
                  th= t('.email')
                  th= t('.payment_email')
                  th= t('.expected_revenue')
                  th= t('.total_payment_method_fee')
                  th= t('.expected_profit')
                  th= t('.category')
                  th= t('.visible')
                  th= t('.can_finish')
                  th= t('.paid')
                  th= t('.success')
                  th= t('.slug')
              tbody
                - @projects.each do |project|
                  tr class=cycle("even", "odd")
                    td= project.id

                    td title=project.name
                      = link_to project_path(project) do
                        = image_tag project.display_image, class: 'project_img'

                    td= project.when_short

                    td= l(project.expires_at)

                    td= l(project.expires_at + 7.day)

                    td title=project.user.display_name
                      = link_to user_path(project.user) do
                        = image_tag project.user.display_image, class: 'user_img'

                    td= project.user.email

                    td= project.user.payment_email

                    td= project.display_expected_revenue

                    td= project.display_total_payment_method_fee

                    td= project.display_expected_profit

                    td= project.category.name

                    td= check_box_tag "project__visible__#{project.id}", '1', project.visible

                    / td= check_box_tag "project__rejected__#{project.id}", '1', project.rejected

                    / td= check_box_tag "project__recommended__#{project.id}", '1', project.recommended

                    td
                      = check_box_tag "project__can_finish__#{project.id}", '1', project.can_finish
                      = (project.finished ? "(x)" : "( )")

                    / td= (project.finished ? t('yes') : t('no'))

                    td= check_box_tag "project__paid__#{project.id}", '1', project.paid

                    td= (project.successful ? I18n.t('yes') : I18n.t('no'))

                    td= on_the_spot_edit project, :permalink, :tooltip => '-'

        = paginate @projects

    .clearfix

app/views/projects/start.html.slim
- content_for :header_featured do
  .project_image
    #banner-create
#page_content
  .container
    .start_content
      .sidebar
        h3= t('.sidebar.title')
        ul
          li
            span.one
            p= t('.sidebar.first_step')
          li
            span.two
            p= t('.sidebar.second_step')
          li
            span.three
            p= t('.sidebar.third_step')
          li
            span.four
            p= t('.sidebar.fourth_step')
            = link_to t('.sidebar.link'), t('site.help'), target: "_blank"
      .main
        .title
          h1= t('.title').html_safe
        .clearfix
        .bootstrap-form
          = form_tag(send_mail_projects_path, :id => 'start_project_form') do
            h2= t('.the_meeting')
            fieldset
              .input
                = label_tag 'name', t('.name')
                = text_field_tag 'name'
                p.inline-hints= t('.name_hint')
              .input
                = label_tag 'about', t('.about')
                = text_area_tag 'about'
                p.inline-hints= t('.about_hint')
              .input
                = label_tag 'when', t('.when')
                = text_field_tag 'when'
                p.inline-hints= t('.when_hint')
              .input
                = label_tag 'where', t('.where')
                = text_area_tag 'where'
                p.inline-hints= t('.where_hint')
              .input
                = label_tag 'video', t('.video')
                = text_field_tag 'video'
                p.inline-hints= t('.video_hint')

            h2= t('.the_people')
            fieldset
              .input
                = label_tag 'leader_name', t('.leader_name')
                = text_field_tag 'leader_name'
                p.inline-hints= t('.leader_name_hint').html_safe
              .input
                = label_tag 'more_info', t('.more_info')
                = text_area_tag 'more_info'
                p.inline-hints= t('.more_info_hint')

            h2= t('.the_registrations')
            fieldset
              .input
                = label_tag 'goal', t('.goal')
                = text_field_tag 'goal'
                p.inline-hints= t('.goal_hint').html_safe
              .input
                = label_tag 'maximum_backers', t('.maximum_backers')
                = text_field_tag 'maximum_backers'
                p.inline-hints= t('.maximum_backers_hint').html_safe
              .input
                = label_tag 'how_works', t('.how_works')
                = text_area_tag 'how_works'
                p.inline-hints= t('.how_works_hint')


            h2= t('.the_contact')
            fieldset
              .input
                = label_tag 'contact', t('.contact')
                .input-prepend
                  span.add-on
                    .bootstrap-twitter
                      i.icon-envelope
                  = text_field_tag 'contact', (current_user.email if current_user)
                  p.inline-hints= t('.contact_hint')
              .input
                = label_tag 'know_us_via', t('.know_us_via')
                = text_area_tag 'know_us_via'
                p.inline-hints= t('.know_us_via_hint')

            .submit
              fieldset.accept
                = check_box_tag 'accept'
                |  
                = label_tag 'accept', t('accept_terms_html', :terms => link_to(t('terms'), terms_path, :target => :_blank), :guidelines => link_to(t('guidelines'), guidelines_path, :target => :_blank), :site => t('site.name')), :class => 'inline'w
              fieldset
                .bootstrap-twitter
                  = submit_tag t('.submit'), :disabled => true, :class => 'btn btn-large'
                  span = t('.submit_complement')
                .clearfix
                = image_tag "loading.gif", :id => 'loading'