config/routes.rb
Catarse::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => {:registrations => "registrations", :passwords => "passwords"} do
    get "/login" => "devise/sessions#new"
    get "/interests" => "users#interests", :as => "user_interests"
  end

  # Non production routes
  if Rails.env == "test"
    match "/fake_login" => "sessions#fake_create", :as => :fake_login
  elsif Rails.env == "development"
    resources :emails, :only => [ :index ]
  end

  mount CatarseMoip::Engine => "/", :as => "catarse_moip"

  filter :locale

  root to: 'projects#index'

  match "/reports/financial/:project_id/backers" => "reports#financial_by_project", :as => :backers_financial_report
  match "/reports/attendance/:project_id/backers" => "reports#attendance_by_project", :as => :backers_attendance_report
  match "/reports/location/:project_id/backers" => "reports#location_by_project", :as => :backers_location_report
  match "/reports/users_most_backed" => "reports#users_most_backed", :as => :most_backed_report
  match "/reports/all_confirmed_backers" => "reports#all_confirmed_backers", :as => :all_confirmed_backers_report
  match "/reports/all_projects_owners" => "reports#all_projects_owner", :as => :all_projects_owner_report
  match "/reports/all_emails" => "reports#all_emails_to_newsletter", :as => :all_emails_to_newsletter
  match "/reports/projects_monthly" => "reports#projects_monthly", :as => :projects_monthly

  # Static Pages
  match '/sitemap' => "static#sitemap", :as => :sitemap
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/terms" => "static#terms", :as => :terms
  match "/privacy" => "static#privacy", :as => :privacy
  match "/about_us" => "static#about_us", :as => :about_us
  match "/contact" => "static#contact", :as => :contact

  match "/thank_you" => "payment_stream#thank_you", :as => :thank_you
  match "/moip" => "payment_stream#moip", :as => :moip
  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  post "/auth" => "sessions#auth", :as => :auth
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout
  resources :posts, only: [:index, :create]
  resources :projects, only: [:index, :new, :create, :show, :update] do
    resources :updates, :only => [:index, :create, :destroy]
    resources :rewards
    resources :backers, controller: 'projects/backers' do
      collection do
        post 'review'
      end
      member do
        put 'checkout'
      end
    end
    collection do
      get 'vimeo'
      get 'cep'
      get 'pending'
      get 'pending_backers'
      get 'thank_you'
      post 'update_attribute_on_the_spot'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    member do
      get 'projects'
      get 'credits'
    end
    post 'update_attribute_on_the_spot', :on => :collection
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  resources :curated_pages do
    collection do
      post 'update_attribute_on_the_spot'
    end
  end
  match "/pages/:permalink" => "curated_pages#show", as: :curated_page

  match "/beta" => redirect("http://nos.vc")
  namespace :adm do
    resources :backers do
      collection do
        post 'update_attribute_on_the_spot'
      end
    end
    resources :users
  end

  resources :tests

  match "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/backer.rb
# coding: utf-8
class Backer < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::DateHelper
  belongs_to :project
  belongs_to :user
  belongs_to :reward
  has_many :payment_logs
  has_one :payment_detail
  has_many :dynamic_values
  validates_presence_of :project, :user, :value
  validates_numericality_of :value, :greater_than_or_equal_to => 0.00
  validate :reward_must_be_from_project
  scope :anonymous, where(:anonymous => true)
  scope :not_anonymous, where(:anonymous => false)
  scope :confirmed, where(:confirmed => true)
  scope :not_confirmed, where(:confirmed => false)
  scope :pending, where(:confirmed => false)
  scope :display_notice, where(:display_notice => true)
  scope :can_refund, where(:can_refund => true)
  scope :within_refund_deadline, where("date(current_timestamp) <= date(created_at + interval '180 days')")
  after_create :define_key, :define_payment_method
  #attr_protected :confirmed
  accepts_nested_attributes_for :dynamic_values

  def define_key
    self.update_attributes({ key: Digest::MD5.new.update("#{self.id}###{self.created_at}###{Kernel.rand}").to_s })
  end

  def define_payment_method
    self.update_attributes({ payment_method: 'MoIP' })
  end

  def price_in_cents
    (self.value * 100).round
  end

  before_save :confirm?

  def confirm?
    if confirmed and confirmed_at.nil?
      self.confirmed_at = Time.now
      self.display_notice = true
    end
  end

  def confirm!
    self.confirmed = true
    self.confirmed_at = Time.now
    self.save
    notify_confirmation
  end

  def reward_must_be_from_project
    return unless reward
    errors.add(:reward, I18n.t('backer.reward_must_be_from_project')) unless reward.project == project
  end

  validate :value_must_be_at_least_rewards_value

  def value_must_be_at_least_rewards_value
    return unless reward
    errors.add(:value, I18n.t('backer.value_must_be_at_least_rewards_value', :minimum_value => reward.display_minimum)) unless value >= reward.minimum_value
  end

  validate :should_not_back_if_maximum_backers_been_reached, :on => :create

  def should_not_back_if_maximum_backers_been_reached
    return unless reward and reward.maximum_backers and reward.maximum_backers > 0
    errors.add(:reward, I18n.t('backer.should_not_back_if_maximum_backers_been_reached')) unless reward.backers.confirmed.count < reward.maximum_backers
  end

  def display_value
    number_to_currency value, :unit => "R$", :precision => 0, :delimiter => '.'
  end

  def display_total_paid
    number_to_currency total_paid, :unit => "R$", :precision => 0, :delimiter => '.'
  end

  def display_confirmed_at
    I18n.l(confirmed_at.to_date) if confirmed_at
  end

  def platform_fee(fee=7.5)
    (value.to_f * fee)/100
  end

  def display_platform_fee(fee=7.5)
    number_to_currency platform_fee(fee), :unit => "R$", :precision => 2, :delimiter => '.'
  end

  def payment_service_fee
    (payment_detail || build_payment_detail.update_from_service).service_tax_amount.to_f
  end

  def moip_value
    "%0.0f" % (value * 100)
  end

  def cancel_refund_request!
    raise I18n.t('credits.cannot_cancel_refund_reques') unless self.requested_refund
    raise I18n.t('credits.refund.refunded') if self.refunded
    raise I18n.t('credits.refund.no_credits') unless self.user.credits >= self.value
    self.update_attributes({ requested_refund: false })
    self.user.update_attributes({ credits: (self.user.credits + self.value) })
  end

  def refund_deadline
    created_at + 180.days
  end

  def as_json(options={})
    json_attributes = {
      :id => id,
      :anonymous => anonymous,
      :confirmed => confirmed,
      :confirmed_at => display_confirmed_at,
      :value => display_value,
      :user => user.as_json(options.merge(:anonymous => anonymous)),
      :display_value => nil,
      :reward => nil
    }
    if options and options[:can_manage]
      json_attributes.merge!({
        :display_value => display_value,
        :reward => reward
      })
    end
    if options and options[:include_project]
      json_attributes.merge!({:project => project})
    end
    if options and options[:include_reward]
      json_attributes.merge!({:reward => reward})
    end
    json_attributes
  end

  protected
  def notify_confirmation
    text = I18n.t('notifications.backers.to_backer.text',
                  :backer_name => user.display_name,
                  :backer_value => display_value,
                  :reward => "#{reward.description if reward}",
                  :city => project.category.name,
                  :date => project.when_long,
                  :project_link => Rails.application.routes.url_helpers.project_url(project, :host => I18n.t('site.host')),
                  :project_name => project.name,
                  :user_name => project.user.display_name,
                  :user_email => project.user.email)
    Notification.create! :user => user,
                         :email_subject => I18n.t('notifications.backers.to_backer.subject', :project => project.name),
                         :email_text => text,
                         :text => text
    text_project_owner = I18n.t('notifications.backers.to_project_owner.text',
                                :backer_name => user.display_name,
                                :backer_email => user.email,
                                :backer_value => display_value,
                                :reward => "#{reward.description if reward}",
                                :project_link => Rails.application.routes.url_helpers.project_url(project, :host => I18n.t('site.host')),
                                :project_name => project.name)
    Notification.create! :user => project.user,
                         :email_subject => I18n.t('notifications.backers.to_project_owner.subject', :backer_name => user.display_name),
                         :email_text => text_project_owner,
                         :text => text_project_owner
  end
end

app/controllers/adm/backers_controller.rb
class Adm::BackersController < Adm::BaseController
  inherit_resources
  menu I18n.t("adm.backers.index.menu") => Rails.application.routes.url_helpers.adm_backers_path
  before_filter :set_title
  before_filter :can_update_on_the_spot?, :only => :update_attribute_on_the_spot

  protected
  def can_update_on_the_spot?
    project_fields = []
    project_admin_fields = ["name", "about", "headline", "can_finish", "expires_at", "user_id", "image_url", "video_url", "visible", "rejected", "recommended", "permalink"]
    backer_fields = ["display_notice"]
    backer_admin_fields = ["confirmed", "requested_refund", "refunded", "anonymous", "user_id"]
    reward_fields = []
    reward_admin_fields = ["description"]
    def render_error; render :text => t('require_permission'), :status => 422; end
    return render_error unless current_user
    klass, field, id = params[:id].split('__')
    return render_error unless klass == 'project' or klass == 'backer' or klass == 'reward'
    if klass == 'project'
      return render_error unless project_fields.include?(field) or (current_user.admin and project_admin_fields.include?(field))
      project = Project.find id
      return render_error unless current_user.id == project.user.id or current_user.admin
    elsif klass == 'backer'
      return render_error unless backer_fields.include?(field) or (current_user.admin and backer_admin_fields.include?(field))
      backer = Backer.find id
      return render_error unless current_user.admin or (backer.user == current_user)
    elsif klass == 'reward'
      return render_error unless reward_fields.include?(field) or (current_user.admin and reward_admin_fields.include?(field))
      reward = Reward.find id
      return render_error unless current_user.admin
    end
  end

  def set_title
    @title = t("adm.backers.index.title")
  end

  def collection
    @search = Backer.search(params[:search])
    @backers = @search.order("created_at DESC").page(params[:page])
  end
end

app/controllers/projects/backers_controller.rb
# Encoding: utf-8
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :new
  before_filter :load_project

  def index
    @backers = @project.backers.confirmed.order("confirmed_at DESC").page(params[:page]).per(20)

    respond_to do |format|
      format.html { redirect_to(login_path) unless can?(:manage_backers, @project) }
      format.json { render :json => @backers.to_json(:can_manage => can?(:manage, @project)) }
    end
  end

  def new
    return unless require_login
    unless @project.can_back?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end
    @title = t('projects.backers.new.title', :name => @project.name)
    @backer = @project.backers.new(:user => current_user)
    #empty_reward = Reward.new(:id => 0, :minimum_value => 0, :description => t('projects.backers.new.no_reward'))
    @rewards = []
    if session[:token].present?
      @rewards = @project.rewards.with_token session[:token]
    end
    @rewards.concat @project.rewards.not_expired.order(:minimum_value).public
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def review
    return unless require_login

    @title = t('projects.backers.review.title')
    params[:backer][:reward_id] = nil if params[:backer][:reward_id] == '0'
    params[:backer][:user_id] = current_user.id
    @project = Project.find params[:project_id]
    backer_data = params[:backer]
    backer_data[:value] = Reward.find(backer_data[:reward_id]).minimum_value
    @backer = @project.backers.new(backer_data)

    unless @backer.save
      raise @backer.errors.inspect
      flash[:failure] = t('projects.backers.review.error')
      return redirect_to new_project_backer_path(@project)
    end
    if @backer.project.has_dynamic_fields?
      @backer.project.dynamic_fields.order(:created_at).each do |dynamic_field|
        @backer.dynamic_values.build dynamic_field_id: dynamic_field.id
      end
    end
    session[:thank_you_id] = @project.id
  end

  def checkout
    return unless require_login
    backer = current_user.backs.find params[:id]
    session[:token] = nil # remove the token of reward
    # reward free
    if backer.value == 0
      current_user.update_attributes params[:user]
      update_dynamic_values_attributes backer
      unless backer.confirmed
        backer.update_attribute :payment_method, 'Free'
        backer.confirm!
      end
      flash[:success] = t('projects.backers.checkout.success')
      return redirect_to thank_you_path
    end

    if params[:payment_method_url].present?
      current_user.update_attributes params[:user]
      current_user.reload
      update_dynamic_values_attributes backer
      return redirect_to params[:payment_method_url]
    else
      if backer.credits
        if current_user.credits < backer.value
          flash[:failure] = t('projects.backers.checkout.no_credits')
          return redirect_to new_project_backer_path(backer.project)
        end
        unless backer.confirmed
          current_user.credits = (current_user.credits - backer.value)
          current_user.save
          backer.update_attributes({ payment_method: 'Credits' })
          backer.confirm!
        end
        flash[:success] = t('projects.backers.checkout.success')
        redirect_to thank_you_path
      end
    end
  end

  private
  def update_dynamic_values_attributes backer
    backer.update_attributes({:dynamic_values_attributes => params[:backer][:dynamic_values_attributes]}) if params[:backer].present? and params[:backer][:dynamic_values_attributes].present?
  end
  def load_project
    @project = Project.find params[:project_id]
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def preview_mode?
    params[:preview] == 'true'
  end

  def show_edit_field
    can?(:edit, @project) && !preview_mode?
  end

  # For the 'past locations' section, generates a list
  # of span tas to be shown
  def generate_location_tags locations
    location_tags = locations.map do |location|
      content_tag :span, location, :class => 'past-location'
    end

    if location_tags.size == 1
      location_tags.first # return the only tag
    else
      # when there are multiple tags join them (the last one is different too)
      last_tag = location_tags.pop

      "#{location_tags.join(', ')} ou #{last_tag}"
    end
  end

end

app/views/projects/backers/_anonymous_warning.en.html.slim
strong Are you sure?
|  If your registration is anonymous it won't show in the meeting page nor your profile page. Even if your registration is not anonymous, the value you paid won't be published anywhere. Only the meeting organizer will be able to see it.

app/views/projects/backers/_back_text.en.html.slim
h3 How is the payment made?
p You'll choose a type of registration and we'll redirect you to #{link_to "MoIP", "http://www.moip.com.br/", :target => :_blank}, Um sistema seguro para pagamentos online de todos os tipos que aceita cartões e transferência bancária,  where you'll be able to finish your payment.

h3 When is the registration confirmed?
p Shortly after #{link_to "MoIP", "http://www.moip.com.br/", :target => :_blank} confirms the transaction. It could take a few minutes, to a few days depending on the choosen bank or method of payment. Free registrations will be confirmed immediately.

h3 How can I register another person for the meeting?
p You can't register another person for this meeting. You could make a payment for someone else, but we suggest that each person register individually. It's a way to affirm that you yourself want to learn and help make the meeting happen. Besides, registrations will be listed on the profile page of the person that made them. If you want to pay for someone else's registration you can personally arrange this with them, for example he/she can register themselves and you'll help them by paying with your credit card or giving them the money afterwards.

h3 What happens if the meeting doesn't reach the minimum number of registrations?
p In case the meeting does not get the minimum number of registrations until #{@project.display_expires_at} the meeting won't happen. You'll get your money back in the form of credits on Nós.vc. Yes, 100% of what you've paid will be returned and can be used to pay for another registration. If your registration was free you'll get back 'good vibes' that you can spend however you want.


h3 What if I don't want to use the credits on Nós.vc?
p No problem. Just go to #{link_to t('credits.title'), credits_path, :target => :_blank}, up until 180 days after your payment, and request a refund. If you've paid with credit card, the refund will be received in your next bill. If you've paid with debit or transfer, the only way to receive the refund is to open an account on MoIP. This way we can transfer the value from our account to yours and, from there, you can transfer it to your bank account. No matter the way you chose to do it, you wont have to pay anything extra.

h3 After I'm registered, how do I participate?
p Just go to the meeting location and intoduce yourself! Any additional information will be sent by  #{link_to @project.user.display_name, user_path(@project.user)}.

app/views/projects/backers/_back_text.pt.html.slim
h3 Como é feito o pagamento?
p Você escolhe sua inscrição e nós te direcionamos para efetuar o pagamento pelo #{link_to "MoIP", "http://www.moip.com.br/", :target => :_blank}. Um sistema seguro para pagamentos online de todos os tipos que aceita cartões e transferência bancária. No cartão, você pode parcelar em até 6x, com juros de 1,99% ao mês.

h3 Quando a inscrição é efetivada?
p Assim que o #{link_to "MoIP", "http://www.moip.com.br/", :target => :_blank} confirmar a transação. Pode demorar alguns minutos ou alguns dias, depende da forma de pagamento e dos bancos. Se a inscrição for gratuita, é efetivada na hora.

h3 Como faço para inscrever outra pessoa?
p Você não pode fazer inscrição para outra pessoa. Mas pode pagar a inscrição por alguém. Nós sugerimos que cada pessoa faça sua própria inscrição. É uma forma de afirmar que ela mesma quer aprender e dar vida ao encontro. Além disso, a inscrição fica registrada apenas no perfil de quem a fez. Se você quiser pagar a inscrição de alguém, o jeito é combinar com o felizardo. Ele faz a própria inscrição e você efetua o pagamento com seu cartão, transferência bancária, ou ressarce a grana depois, por exemplo.

h3 O que acontece se o encontro não atingir o número mínimo de inscritos?

p Caso não atinja o número mínimo de inscritos até #{@project.display_expires_at}, o encontro não será realizado. Você receberá seu dinheiro de volta na forma de créditos no #{t('site.name')}. Isso mesmo, 100% do valor volta praf ser utilizado em outra inscrição. Ou, se a inscrição for gratuita, você vai receber good vibes para gastar como quiser.
h3 E se eu não quiser usar os créditos no #{t('site.name')}?

p Tudo bem! É só entrar em #{link_to t('credits.title'), credits_path, :target => :_blank}, no seu perfil, e solicitar um estorno, em até 180 dias após sua inscrição. Se você pagou com cartão de crédito, o estorno será feito na sua próxima fatura. Se pagou com débito em conta, a única maneira de fazer o estorno é através de uma conta no MoIP que você pode abrir gratuitamente. A gente vai transferir o valor da nossa conta para a sua e, de lá, você transfere para sua conta no banco. De qualquer forma, você não terá nenhuma despesa.

h3 Depois de fazer a inscrição, como faço para participar?
p É só chegar e se apresentar! Qualquer informação adicional será enviada por #{link_to @project.user.display_name, user_path(@project.user)}.

app/views/projects/backers/new.html.slim
- content_for :header_featured do
  .project_image
    =image_tag @project.display_image

#page_content
  .container
    .sidebar
      #back_info
        .back_faq
          .tittle
            = t('.good_question')
          = render 'back_text'
      .clearfix
    .main
      .backer_content
        .title
          h1= t('.header.title')
        #project_info
          .project_name= link_to @project.name, project_path(@project)
          .infos
            .project_owner #{t('by')} #{link_to @project.user.display_name, user_path(@project.user)}
            .when= @project.when_short
            .location= @project.category.name
        .clearfix  
        #back_options.bootstrap-form
          = semantic_form_for @backer, :url => review_project_backers_path(@project), :html => { :id => 'backer_form' } do |form|
            = form.inputs do
              = hidden_field_tag 'credits', ("%0.0f" % current_user.credits)
              = form.input :value, :required => false, :as => :hidden
              - if current_user.credits >= @rewards.first.minimum_value and @rewards.first.minimum_value > 0
                .bootstrap-alert
                  .alert.alert-info
                    = form.input :credits, :hint => t('formtastic.hints.backer.credits', :credits => current_user.display_credits).html_safe
              script
                | var rewards = new Array(); 
                - @rewards.each do |reward|
                   = "rewards[#{reward.id || 0}] = #{reward.minimum_value}; "
              = form.input :reward, :as => :radio, :collection => @rewards
              = form.input :anonymous
              #anonymous_warning.important.hide
                .bootstrap-alert
                  .alert
                    = render 'anonymous_warning'
            = form.actions do
              .bootstrap-twitter
                = form.submit t('.submit'), :disabled => true, :class => 'btn btn-primary btn-large', :id => "backer_submit"
                span = t('projects.backers.new.and_make_it_happen')
        .cards
          h3 = 'Através do moip aceitamos:'
          ul
            li.cartao
              p = 'Cartões em até 6x. 1,99%(a.m)'
            li.transferencia
              p = 'Transferência'

app/views/projects/backers/review.html.haml
#page_content
  .container
    #project_review
      .project_info
        = image_tag @project.display_image, :id => 'project_image', :alt => @project.name, :width => '250px'
        %h1= t('.you_are_about_html', :link => link_to(@project.name, project_path(@project)))
        #review_text
          - if @backer.reward
            = t('.review_with_reward_html', :value => @backer.display_value, :reward => @backer.reward.description)
          - else
            = t('.review_without_reward_html', :value => @backer.display_value)
      .clearfix
      .title
        %h1= t('.title')
        %h2= t('.subtitle')
      .clearfix
      - if @backer.credits
        #back_with_credits
          .bootstrap-alert
            .alert
              #credits_notice= t('.credits_notice_html', :credits => number_to_currency((current_user.credits - @backer.value), :unit => 'R$', :precision => 0, :delimiter => '.'))
      - else
      .bootstrap-form
        = semantic_form_for current_user, :url => checkout_project_backer_path(@backer.project, @backer), :html => { :id => 'review_form', :class => "form-horizontal #{('dont_align' if @backer.credits)}" } do |form|
          = hidden_field_tag 'backer_id', @backer.id
          = hidden_field_tag 'backer_credits', @backer.credits
          - unless @backer.credits
            = form.inputs do
              = form.input :full_name, :required => true, :as => :string
              = form.input :cpf, :as => :string, :input_html => {:autocomplete => 'off'}
              = form.input :email, :required => true, :as => :string
              = form.input :address_street, :as => :string
              = form.input :address_number, :as => :string
              = form.input :address_complement, :required => false, :as => :string
              = form.input :address_neighbourhood, :as => :string
              = form.input :address_zip_code, :as => :string, :input_html => {:autocomplete => 'off'}
              = form.input :address_city, :as => :string
              = form.input :address_state, :as => :select, :collection => State.array
              = form.input :phone_number, :as => :string, :input_html => {:autocomplete => 'off'}
          .submit
            %fieldset.accept_terms
              = check_box_tag 'accept'
              = label_tag 'accept', t('accept_terms_html', :link => link_to(t('terms'), terms_path, :target => :_blank)), :class => 'inline'
            - if @backer.credits
              = form.actions do
                .bootstrap-twitter
                  = form.submit (@backer.credits ? t('.submit.credits') : t('.submit.moip')), :disabled => true, :class => 'btn', :id => 'user_submit'
          #payment.hide
            - if @backer.value > 0
              .title
                %h1= t('.choose_payment')
              .choose_payment
                .cc
                  = link_to pay_paypal_path(@backer), :method => :get do
                    = image_tag 'catarse/cc_icon.png'
                    %span= t('.choose_credit_card')
                  .clearfix
                .or
                  %span= t('or')
                .boleto
                  = link_to checkout_project_backer_path(@backer.project, @backer), :method => :put do
                    = image_tag 'catarse/boleto_icon.png'
                    %span= t('.choose_boleto')
            - elsif @backer.value == 0
              .title
                %h1= t('.choose_free')
              .free
                = link_to checkout_project_backer_path(@backer.project, @backer), :method => :put do
                  = image_tag 'catarse/cc_icon.png'
                  %span= t('.confirm_free')
                .clearfix

    .clearfix

app/views/projects/backers/review.html.slim
- content_for :header_featured do
  .project_image
    =image_tag @project.display_image

#page_content
  .container
    .sidebar
      #review_text
        h1 = @backer.value > 0 ? @backer.display_value : I18n.t('reward.free')
        p= @backer.reward.description
      .clearfix
    .main
      .title
        h1= t('.you_are_about_html', :link => link_to(@project.name, project_path(@project)))
        h2= t('.subtitle')
      .clearfix
      - if @backer.credits
        #back_with_credits
          .bootstrap-alert
            .alert
              #credits_notice= t('.credits_notice_html', :credits => number_to_currency((current_user.credits - @backer.value), :unit => 'R$', :precision => 0, :delimiter => '.'))
      .bootstrap-form
        = semantic_form_for current_user, :url => checkout_project_backer_path(@backer.project, @backer), :html => { :id => 'review_form', :class => "form-horizontal #{('dont_align' if @backer.credits)}" } do |form|
          = hidden_field_tag 'backer_id', @backer.id
          = hidden_field_tag 'backer_credits', @backer.credits
          = hidden_field_tag 'payment_method_url', nil
          - unless @backer.credits
            = form.inputs do
              = form.input :full_name, :required => true, :as => :string
              = form.input :cpf, :as => :string, :input_html => {:autocomplete => 'off'}
              = form.input :email, :required => true, :as => :string
              = form.input :address_street, :as => :string
              = form.input :address_number, :as => :string
              = form.input :address_complement, :required => false, :as => :string
              = form.input :address_neighbourhood, :as => :string
              = form.input :address_zip_code, :as => :string, :input_html => {:autocomplete => 'off'}
              = form.input :address_city, :as => :string
              = form.input :address_state, :as => :select, :collection => State.array
              = form.input :phone_number, :as => :string, :input_html => {:autocomplete => 'off'}
              - if @backer.project.has_dynamic_fields?
                #dynamic_values_wrapper
                  = semantic_fields_for @backer do |backer|
                    = backer.semantic_fields_for :dynamic_values do |dynamic_value|
                      - dynamic_field = DynamicField.find dynamic_value.object.dynamic_field_id
                      .dynamic_value
                        = dynamic_value.input :dynamic_field_id, :as => :hidden
                        = dynamic_value.input :value, :label => "#{dynamic_field.input_name}:", :hint => "", :required => dynamic_field.required, :input_html => { :"data-validate-presence" => dynamic_field.required == true }

          .submit
            fieldset.accept_terms
              = check_box_tag 'accept'
              = label_tag 'accept', t('accept_terms_html', :terms => link_to(t('terms'), terms_path, :target => :_blank), :guidelines => link_to(t('guidelines'), guidelines_path, :target => :_blank), :site => t('site.name')), :class => 'inline'
            - if @backer.credits
              = form.actions do
                .bootstrap-twitter
                  = form.submit t('.submit.credits'), :disabled => true, :class => 'btn', :id => 'user_submit'
          - unless @backer.credits
            #payment.hide
              - if @backer.value > 0
                .choose_payment
                  .moip
                    = link_to t('.confirm_payment'),  'javascript:void(0);', :"data-payment_method_url" => catarse_moip.pay_payment_moip_path(@backer), :method => :get, :class => 'payment_link'
                    span= t('.confirm_payment_hind')
              - elsif @backer.value == 0
                .free
                  = link_to t('.confirm_free'), "javascript: $('form#review_form')[0].submit();"
                  span
                    = t('.confirm_free_hind')
                  .clearfix
            .payment_disabled
              .bootstrap-twitter
                = submit_tag t('.submit'), :disabled => true, :class => 'btn btn-large'
    .clearfix